### ISSUE TITLE
Can I improve your code?

### ISSUE THREAD

**Issue by RedFurrFox** [slurb/yiffer.xyz-downloader#1]
I will try to add some improvements to your code for free, and fully documented

**Comment by slurb** [comment]
Yes! Go for it dude add whatever you like, I just made it as a quick project.

**Comment by RedFurrFox** [comment]
Thanksssss!

**Comment by slurb** [comment]
Thank you for helping make this repo better! Also your code helped me learn new things :)

**Comment by RedFurrFox** [comment]
No problemo bro, tag me to any of your repos if you need some extra helping hand 👌
